app = "fooocus-demo"
primary_region = "ord"

[http_service]
  internal_port = 7865
  force_https = true

[mounts]
  source = "models"
  destination = "/app/Fooocus/models"
  initial_size = "20gb"

[[vm]]
  size = "performance-8x"
  memory = "32gb"
  gpu_kind = "a100-pcie-40gb"
